"""
Test Dataloader Visualization Server

Serves the visualizations generated by test_dataloader.py --visualize.

Usage:
    python serve_test_vis.py              # Serve visualizations
    python serve_test_vis.py --port 8001  # Use custom port
"""

import os
import sys
import argparse
from pathlib import Path
from http.server import SimpleHTTPRequestHandler
from socketserver import ThreadingTCPServer

SCRIPT_DIR = Path(__file__).parent
VIS_PATH = SCRIPT_DIR / "test_visualizations"
DEFAULT_PORT = 8001


def main():
    parser = argparse.ArgumentParser(description="Serve test dataloader visualizations")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="Port to serve on")
    args = parser.parse_args()
    
    # Check if visualization exists
    if not VIS_PATH.exists():
        print(f"Error: Visualization directory not found: {VIS_PATH}")
        print(f"\nRun test_dataloader.py --visualize first to generate visualizations")
        sys.exit(1)
    
    # Check for index.html
    index_file = VIS_PATH / "index.html"
    if not index_file.exists():
        print(f"Error: index.html not found in {VIS_PATH}")
        print(f"\nRun test_dataloader.py --visualize first to generate visualizations")
        sys.exit(1)
    
    # Count available samples
    sample_files = list(VIS_PATH.glob("sample_*_2d.png"))
    sample_3d_files = list(VIS_PATH.glob("sample_*_3d.html"))
    
    print(f"\nTest Dataloader Visualization Server")
    print(f"{'='*40}")
    print(f"Visualization path: {VIS_PATH}")
    print(f"2D samples: {len(sample_files)}")
    print(f"3D samples: {len(sample_3d_files)}")
    print(f"{'='*40}\n")
    
    # Change to vis directory and serve
    os.chdir(VIS_PATH)
    
    host = "127.0.0.1"
    port = args.port
    
    httpd = ThreadingTCPServer((host, port), SimpleHTTPRequestHandler)
    
    print(f"Serving at: http://{host}:{port}")
    print(f"Press Ctrl+C to stop.\n")
    
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
        httpd.server_close()


if __name__ == "__main__":
    main()

